- air_date
- aliases
- api_detail_url
- character_credits
- character_died_in
- concept_credits
- date_added
- date_last_updated
- deck
- description
- episode_number
- first_appearance_characters
- first_appearance_concepts
- first_appearance_locations
- first_appearance_objects
- first_appearance_storyarcs
- first_appearance_teams
- has_staff_review
- id
- image
- location_credits
- name
- object_credits
- series
- site_detail_url
- story_arc_credits
- team_credits
