- aliases
- api_detail_url
- count_of_isssue_appearances
- date_added
- date_last_updated
- deck
- description
- episodes
- first_appeared_in_episode
- first_appeared_in_issue
- id
- image
- issues
- movies
- name
- publisher
- site_detail_url
