- api_detail_url
- box_office_revenue
- budget
- characters
- concepts
- date_added
- date_last_updated
- deck
- description
- distributor
- has_staff_review
- id
- image
- locations
- name
- objects
- producers
- rating
- release_date
- runtime
- site_detail_url
- studios
- teams
- total_revenue
- writers
