- aliases
- api_detail_url
- characters
- concepts
- count_of_issues
- date_added
- date_last_updated
- deck
- description
- first_issue
- id
- image
- issues
- last_issue
- name
- objects
- people
- publisher
- site_detail_url
- start_year
