- aliases
- api_detail_url
- character_enemies
- character_friends
- characters
- count_of_isssue_appearances
- count_of_team_members
- date_added
- date_last_updated
- deck
- description
- disbanded_in_issues
- first_appeared_in_issue
- id
- image
- isssues_disbanded_in
- issue_credits
- movies
- name
- publisher
- site_detail_url
- story_arc_credits
- volume_credits
