- aliases
- api_detail_url
- birth
- count_of_isssue_appearances
- country
- created_characters
- date_added
- date_last_updated
- death
- deck
- description
- email
- gender
- hometown
- id
- image
- issues
- name
- site_detail_url
- story_arc_credits
- volume_credits
- website
