- aliases
- api_detail_url
- characters
- date_added
- date_last_updated
- deck
- description
- id
- image
- location_address
- location_city
- location_state
- name
- site_detail_url
- story_arcs
- teams
- volumes
