- aliases
- api_detail_url
- count_of_issue_appearances
- date_added
- date_last_updated
- deck
- description
- first_appeared_in_issue
- id
- image
- issue_credits
- movies
- name
- site_detail_url
- start_year
- story_arc_credits
- volume_credits
