- aliases
- api_detail_url
- character_credits
- character_died_in
- concept_credits
- cover_date
- date_added
- date_last_updated
- deck
- description
- first_appearance_characters
- first_appearance_concepts
- first_appearance_locations
- first_appearance_objects
- first_appearance_storyarcs
- first_appearance_teams
- has_staff_review
- id
- image
- issue_number
- location_credits
- name
- object_credits
- person_credits
- site_detail_url
- store_date
- story_arc_credits
- team_credits
- team_disbanded_in
- volume
