- aliases
- api_detail_url
- characters
- count_of_episodes
- date_added
- date_last_updated
- deck
- description
- episodes
- first_episode
- id
- image
- last_episode
- name
- publisher
- site_detail_url
- start_year
